//============================================================================
//  Power Spikes -- where each ROM region lives in SDRAM
//
//  GENERATED by tools/build_rom.py --svh.  Do not edit: REGIONS in that
//  script is the single source of truth for the .mra, the download image and
//  this header.  If they disagree the core loads real ROM data at the wrong
//  addresses and every symptom looks like a decode bug.
//
//      region      byte base    size      word base
//      maincpu     0x000000     256 K   0x000000
//      gfx1        0x040000     512 K   0x020000
//      gfx2        0x0C0000    1024 K   0x060000
//      soundbank   0x1C0000     128 K   0x0E0000
//      adpcma      0x1E0000    1024 K   0x0F0000
//      adpcmb      0x2E0000     256 K   0x170000
//      total       0x320000    3200 K
//
//  SDRAM is addressed in 16-bit words and the download image is bytes, so
//  every word base is the byte base / 2.  Word W holds byte 2W in bits
//  [15:8] and byte 2W+1 in [7:0] -- big-endian, which is what the 68000
//  wants and what ps_download writes.
//============================================================================

localparam [24:0] MAINCPU_BASE_W    = 25'h000000;
localparam [24:0] GFX1_BASE_W    = 25'h020000;
localparam [24:0] GFX2_BASE_W    = 25'h060000;
localparam [24:0] SNDROM_BASE_W    = 25'h0E0000;
localparam [24:0] ADPCMA_BASE_W    = 25'h0F0000;
localparam [24:0] ADPCMB_BASE_W    = 25'h170000;

localparam [24:0] ROM_TOTAL_W    = 25'h190000;
