//============================================================================
//  Power Spikes -- board top
//
//  This is the arcade board and nothing else.  No hps_io, no ioctl, no APF,
//  no MRA: those live in targets/, per root CLAUDE.md section 4.  What
//  crosses this boundary is a neutral memory port (mem_*), neutral inputs,
//  and video/audio out.
//
//  ---- clocking ----------------------------------------------------------
//  clk = 40.000 MHz, and every board clock divides from it exactly:
//
//      68000    10.000 MHz   / 4     HW_CONFIRMED (20 MHz XTAL / 2)
//      Z80       5.000 MHz   / 8     HW_CONFIRMED (20 MHz XTAL / 4)
//      YM2610    8.000 MHz   / 5     HW_CONFIRMED (own 8 MHz XTAL)
//
//  The pixel clock does not divide from it: the board has a second crystal
//  (14.31818 MHz) and 7.159090 MHz is not a rational divisor of 40 MHz by
//  any small integer.  It is generated by a fractional enable instead --
//  add 63, wrap at 352 -- which gives exactly 40e6 * 63/352 = 7.1590909 MHz
//  on average, with pulses alternating 5 and 6 clocks apart.
//
//  Why one clock domain and not two: the alternative is a second PLL output
//  at 57.27 MHz and a real CDC at every dual-port RAM.  Root CLAUDE.md 1.5
//  and section 2 both treat clock/CDC structure as the highest-risk thing to
//  get wrong, and the jitter here is 12.5 ns on a 139.7 ns pixel, which the
//  scaler resamples away.  See docs/DECISIONS.md.
//
//  ---- what is implemented ----------------------------------------------
//      68000, full address decode, all board RAM      yes
//      video timing, tilemap, palette                 yes
//      VS8904/8905 sprites                            yes
//      Z80 + YM2610                                   yes
//============================================================================
`default_nettype none

module ps_top #(
    // Video line counts, owned by ps_crtc and passed down so that the
    // diagnostics below and the timing generator cannot disagree.
    // Nine bits wide, not `int`, on purpose: narrowing a 32-bit int into a
    // 9-bit localparam is a truncation warning and this project ships zero of
    // those, while part-selecting an int parameter -- the other way round --
    // is shaky in Quartus 17.0.  256 and 240 both fit, and ps_video's `int`
    // parameters widen them back without complaint.
    parameter [8:0] V_TOTAL   = 9'd256,
    parameter [8:0] V_VISIBLE = 9'd240,
    parameter int   H_VISIBLE = 352,
    parameter int   H_TOTAL   = 456
) (
    input  wire        clk,            // 40.000 MHz
    input  wire        rst,
    input  wire        mem_rst,        // memory transport must run during load
    input  wire        pause,          // player pause (R, OSD open): immediate
    input  wire        pause_dbg,      // Debug "Pause CPU": armed after a delay

    // --- neutral memory port (ROM/sample data) -----------------------------
    output wire [24:0] mem_addr,
    output wire [15:0] mem_din,
    input  wire [15:0] mem_dout,
    output wire        mem_req,
    output wire        mem_we,
    output wire [1:0]  mem_ds,
    input  wire        mem_ack,

    // --- download (target drives this while loading) ------------------------
    input  wire        dl_active,
    input  wire [24:0] dl_addr,
    input  wire [15:0] dl_data,
    input  wire        dl_req,
    output wire        dl_ack,

    // --- inputs -------------------------------------------------------------
    input  wire [15:0] in0,
    input  wire [15:0] in1,
    input  wire [15:0] dsw,

    // --- video --------------------------------------------------------------
    output wire [7:0]  red,
    output wire [7:0]  green,
    output wire [7:0]  blue,
    output wire        hsync,
    output wire        vsync,
    output wire        hblank,
    output wire        vblank,
    output wire        ce_pix,

    // --- audio --------------------------------------------------------------
    output wire signed [15:0] snd_l,
    output wire signed [15:0] snd_r,

    // --- observability ------------------------------------------------------
    output wire [23:1] dbg_addr,
    output wire        dbg_rd,
    output wire        dbg_wr,
    output wire        dbg_ack,
    output wire [15:0] dbg_din,
    output wire        dbg_vbl_irq,
    output wire        dbg_halted_n,
    output wire [15:0] dbg_cpu_stall,
    output wire [8:0]  dbg_hcnt,
    output wire [8:0]  dbg_vcnt,
    output wire [7:0]  dbg_gfxbank,
    output wire [7:0]  dbg_sound_latch,
    // GGA registers 0 and 8.  docs/HARDWARE.md section 3 says Power Spikes
    // writes 0x57 and 0x77 there; reading them back off real hardware turns
    // that from a MAME comment into a measurement.
    output wire [15:0] dbg_gga,
    // The rest of the timing registers, {01,09} {02,0a} {03,0b} {04,0c}, and
    // what ps_crtc counted.  Together with dbg_gga they put the register
    // values and the timing they produced on ONE overlay page.
    output wire [63:0] dbg_gga_x,
    output wire [79:0] dbg_crtc,
    // {frames with no IACK, IRQ still pending at end of vblank, frames with
    // two or more IACKs} -- cumulative, saturating.  See the IRQ block.
    output wire [31:0] dbg_iack_x,
    output wire [15:0] dbg_spr_drawn,
    output wire [15:0] dbg_spr_hit,
    output wire [15:0] dbg_rom_w0,
    output wire [15:0] dbg_rom_w1,
    output wire        dbg_probe_done,
    output wire [15:0] dbg_spr_overrun,
    output wire [15:0] dbg_spr_snap1,
    output wire [15:0] dbg_spr_snap2,
    output wire [15:0] dbg_spr_nonrom,
    output wire [15:0] dbg_spr_workload,
    output wire [15:0] dbg_z80_cyc,
    output wire [15:0] dbg_ym_wr,
    output wire [15:0] dbg_pcma_fetch,
    output wire [15:0] dbg_pcm_late,
    output wire [7:0]  dbg_snd_state,
    output wire [15:0] dbg_snd_rom_w0,
    output wire [15:0] dbg_snd_rom_n,
    output wire [15:0] dbg_snd_peak,
    output wire [15:0] dbg_snd_latch_ack,
    output wire [15:0] dbg_snd_peak_l,
    output wire [15:0] dbg_snd_peak_r,
    output wire [15:0] dbg_snd_pcma_kon,
    output wire [15:0] dbg_snd_fm_kon,
    output wire [15:0] dbg_snd_sample,
    output wire [15:0] dbg_snd_io_rd,
    output wire [15:0] dbg_snd_last_b1,
    output wire [15:0] dbg_snd_irq,
    output wire [15:0] dbg_snd_intack,
    output wire [15:0] dbg_snd_timer_w,
    output wire [15:0] dbg_snd_peak_fm,
    output wire [15:0] dbg_snd_peak_psg,
    output wire [15:0] dbg_raster_msg,
    output wire [15:0] dbg_raster_court,
    output wire [15:0] dbg_o6_map,
    output wire [15:0] dbg_o6_tile,
    output wire [15:0] dbg_o6_pos,
    output wire [15:0] dbg_o6_first,
    output wire [15:0] dbg_o6_sx,
    output wire [15:0] dbg_o6_blitx,
    output wire [15:0] dbg_o6_row0,
    output wire [15:0] dbg_o6_row1,
    output wire [15:0] dbg_o6_row2,
    output wire [15:0] dbg_o6_row3,
    output wire [15:0] dbg_burst_first,
    output wire [15:0] dbg_tm_late,
    output wire [15:0] dbg_tm_late_l,   // {first third, hcnt >= 215}
    output wire [15:0] dbg_pcma_late_fr,
    output wire [15:0] dbg_pcma_fetch_fr,
    output wire [15:0] dbg_jump_fr,
    output wire [15:0] dbg_maxd_fr,
    output wire [15:0] dbg_sprwr_disp,
    output wire [15:0] dbg_vramwr_disp,
    output wire [15:0] dbg_snd_roe_a,
    output wire [15:0] dbg_snd_peak_op,
    output wire [15:0] dbg_snd_aon_cnt,
    output wire [15:0] dbg_snd_eg_min,
    output wire [15:0] dbg_snd_keyon_cnt,
    output wire [15:0] dbg_snd_mmr_kon,
    output wire [15:0] dbg_snd_kon_latch,
    output wire [15:0] dbg_snd_kon_match,
    output wire [15:0] dbg_snd_csr_slots,
    output wire [15:0] dbg_snd_fm_koff,
    output wire [15:0] dbg_snd_last_kon
);

  `include "ps_rommap.svh"

  // ---------------------------------------------------------------------
  // Clock enables
  // ---------------------------------------------------------------------
  // The DEBUG pause bit is DELAYED, and that is the whole point of it.
  // Only `pause_dbg` goes through this.  The player's pause (`pause`: the R
  // button and "Pause when OSD open") must act at once -- until 2026-09-15 it
  // was OR-ed into the same input and so did nothing for the first ~50 s
  // after every load.
  //
  // Pausing from reset freezes the 68000 before it has booted, so the screen
  // stays black and there is nothing to photograph -- tried, on hardware.
  // What the measurement needs is the opposite: let the game run into the
  // attract, reach a sprite-dense scene, and only then stop the CPU.  The
  // video engines keep scanning and keep contending for SDRAM, so the picture
  // is static while the renderer is still live, and two screenshots then
  // differ ONLY by what the renderer does differently between frames.
  //
  // ~50 s at 61.31 Hz lands in the demo match, which MAME's own dump shows
  // carrying 71 active sprites against 7 on the title screens.
  localparam int PAUSE_DELAY_FRAMES = 3065;
  reg [11:0] pause_fr;
  reg        pause_armed;
  always @(posedge clk) begin
    if (rst) begin
      pause_fr    <= 12'd0;
      pause_armed <= 1'b0;
    end else if (vblank_start && !pause_armed) begin
      if (pause_fr == PAUSE_DELAY_FRAMES[11:0]) pause_armed <= 1'b1;
      else                                      pause_fr <= pause_fr + 12'd1;
    end
  end

  wire ce_en = ~(pause | (pause_dbg & pause_armed)) & ~dl_active;

  // Fractional pixel enable: 40 MHz * 63/352 = 7.1590909 MHz.
  reg [8:0] pixacc;
  reg       ce_pix_r;
  always @(posedge clk) begin
    if (rst) begin
      pixacc   <= 9'd0;
      ce_pix_r <= 1'b0;
    end else begin
      if (pixacc + 9'd63 >= 9'd352) begin
        pixacc   <= pixacc + 9'd63 - 9'd352;
        ce_pix_r <= 1'b1;
      end else begin
        pixacc   <= pixacc + 9'd63;
        ce_pix_r <= 1'b0;
      end
    end
  end
  assign ce_pix = ce_pix_r;

  // ---------------------------------------------------------------------
  // Board RAM shared between the CPU and the video scanner.
  //
  // True dual-port: the CPU port is free-running and the video port reads
  // once per pixel or once per line.  On the real board the GGA arbitrates
  // CPU access against the scan; here both ports are independent, which is
  // strictly more permissive.  If the game turns out to depend on being
  // held off during active display, that is a real difference -- nothing
  // observed so far says it does.                              INFERRED
  // ---------------------------------------------------------------------
  wire [11:1] c_vram_a, c_raster_a, c_pal_a;
  wire [ 9:1] c_spr_a;
  wire [13:1] c_sprlut_a;
  wire [15:0] c_vram_d, c_spr_d, c_raster_d, c_pal_d, c_sprlut_d;
  wire [15:0] c_vram_q, c_raster_q, c_pal_q, c_sprlut_q;
  wire [ 1:0] c_vram_we, c_spr_we, c_raster_we, c_pal_we, c_sprlut_we;

  wire [10:0] v_vram_a, v_raster_a, v_pal_a;
  wire [15:0] v_vram_q, v_raster_q, v_pal_q;
  wire [ 8:0] v_spr_a;
  wire [12:0] v_sprlut_a;
  wire [15:0] v_spr_q, v_sprlut_q;

  ps_dpram #(.AW(11)) u_vram (
      .clk(clk),
      .a_addr(c_vram_a), .a_din(c_vram_d), .a_we(c_vram_we), .a_dout(c_vram_q),
      .b_addr(v_vram_a), .b_dout(v_vram_q));

  ps_dpram #(.AW(11)) u_raster (
      .clk(clk),
      .a_addr(c_raster_a), .a_din(c_raster_d), .a_we(c_raster_we),
      .a_dout(c_raster_q),
      .b_addr(v_raster_a), .b_dout(v_raster_q));

  ps_dpram #(.AW(11)) u_pal (
      .clk(clk),
      .a_addr(c_pal_a), .a_din(c_pal_d), .a_we(c_pal_we), .a_dout(c_pal_q),
      .b_addr(v_pal_a), .b_dout(v_pal_q));

  ps_dpram #(.AW(13)) u_sprlut (
      .clk(clk),
      .a_addr(c_sprlut_a), .a_din(c_sprlut_d), .a_we(c_sprlut_we),
      .a_dout(c_sprlut_q),
      .b_addr(v_sprlut_a), .b_dout(v_sprlut_q));

  // Sprite RAM is write-only from the CPU (MAME maps it .writeonly()), so
  // its A-port read is unused; the sprite engine reads it on the B port.
  ps_dpram #(.AW(9)) u_sprram (
      .clk(clk),
      .a_addr(c_spr_a), .a_din(c_spr_d), .a_we(c_spr_we), .a_dout(),
      .b_addr(v_spr_a), .b_dout(v_spr_q));

  // ---------------------------------------------------------------------
  // Main CPU board
  // ---------------------------------------------------------------------
  // CPU side of the ROM cache (what ps_main sees)...
  wire [17:1] cpu_rom_a;
  wire [15:0] cpu_rom_q;
  wire        cpu_rom_rd, cpu_rom_ack;
  // ...and the memory side (what the arbiter sees).  Every fetch used to go
  // straight through; docs/DECISIONS.md D12 and rtl/memory/ps_romcache.sv say
  // why it no longer does.
  wire [17:1] rc_a;
  wire [15:0] rc_q;
  wire        rc_rd, rc_ack;

  ps_romcache u_romcache (
      .clk(clk), .rst(rst),
      .c_a(cpu_rom_a), .c_rd(cpu_rom_rd), .c_ack(cpu_rom_ack), .c_q(cpu_rom_q),
      .m_a(rc_a),      .m_rd(rc_rd),      .m_ack(rc_ack),      .m_q(rc_q)
  );
  wire        cpu_iack;      // 68000 interrupt-acknowledge cycle

  wire [7:0]  gfxbank, sound_latch;
  wire [1:0]  spr_palbank;
  wire [2:0]  char_palbank;
  wire        flip_screen, sound_latch_we;
  wire [8:0]  scrolly;
  wire [7:0]  gga_regs [0:15];
  wire [15:0] gga_written;
  wire        vblank_start;

  ps_main u_main (
      .clk(clk), .rst(rst), .ce_en(ce_en), .cpu_rst(dl_active),
      .rom_addr(cpu_rom_a), .rom_data(cpu_rom_q),
      .rom_rd(cpu_rom_rd), .rom_ack(cpu_rom_ack),
      .vram_addr(c_vram_a), .vram_din(c_vram_d),
      .vram_dout(c_vram_q), .vram_we(c_vram_we),
      .spr_addr(c_spr_a), .spr_din(c_spr_d), .spr_we(c_spr_we),
      .raster_addr(c_raster_a), .raster_din(c_raster_d),
      .raster_dout(c_raster_q), .raster_we(c_raster_we),
      .pal_addr(c_pal_a), .pal_din(c_pal_d),
      .pal_dout(c_pal_q), .pal_we(c_pal_we),
      .sprlut_addr(c_sprlut_a), .sprlut_din(c_sprlut_d),
      .sprlut_dout(c_sprlut_q), .sprlut_we(c_sprlut_we),
      .gfxbank(gfxbank), .spr_palbank(spr_palbank),
      .char_palbank(char_palbank), .flip_screen(flip_screen),
      .scrolly(scrolly), .gga_regs(gga_regs), .gga_written(gga_written),
      .sound_latch(sound_latch), .sound_latch_we(sound_latch_we),
      .sound_pending(snd_pending),
      .in0(in0), .in1(in1), .dsw(dsw),
      .vblank_irq(vbl_irq),
      .iack_stb(cpu_iack),
      .dbg_addr(dbg_addr), .dbg_rd(dbg_rd), .dbg_wr(dbg_wr),
      .dbg_dout(), .dbg_din(dbg_din), .dbg_ack(dbg_ack),
      .dbg_d7(), .dbg_halted_n(dbg_halted_n)
  );

  // ---------------------------------------------------------------------
  // VBlank interrupt.  MAME uses `irq1_line_hold`, and HOLD_LINE means held
  // until the CPU ACKNOWLEDGES it -- MAME clears it in its IRQ callback.
  //
  // This used to clear it at the END OF VBLANK instead, on the reasoning that
  // fx68k did not expose an acknowledge and "the game's handler always
  // completes well inside one frame".  That was tagged INFERRED and it was
  // wrong in a way that mattered: the handler completes well inside VBLANK,
  // returning around line 7 of 16, and the interrupt was still asserted --
  // so the 68000 took it again immediately and ran the whole handler a
  // second time, every frame.
  //
  // fx68k does announce the acknowledge; the wrapper simply was not passing
  // it out.  FC = 111 with AS low is an interrupt acknowledge cycle.
  // docs/DEBUG_LOG.md O10.
  // ---------------------------------------------------------------------
  //
  // Cleared at the END of the acknowledge cycle, not at its start.  Dropping
  // the level WHILE the 68000 is acknowledging lets it sample level 0 and
  // take a spurious interrupt instead: the first version cleared on the
  // `cpu_iack` level and the board ran for one frame and then froze, with the
  // last captured frame showing zero ROM fetches in its vblank.
  //
  // There used to be a fallback here: if the acknowledge was never seen, the
  // level was dropped at the end of vblank, so that a missed IACK degraded to
  // the old double-handler behaviour instead of a frozen board.  Real
  // hardware has no such path -- the flip-flop is cleared by the acknowledge
  // and by nothing else -- and on the board the acknowledge arrives exactly
  // once a frame (overlay row 68, DEBUG_LOG O22), so it was removed
  // 2026-10-06.  `pend_eovb` below counts the frames in which it WOULD have
  // fired, so if the acknowledge is ever lost again it is visible as a
  // number and not only as a freeze.
  //
  // Set only while the 68000 is running.  A paused CPU (OSD pause, the R
  // button, a ROM download) sees no time pass, and an interrupt latched
  // during the pause would otherwise be taken the moment it resumed -- in
  // the middle of a displayed frame, which the fallback used to hide by
  // dropping it at the end of vblank.  While the CPU runs ce_en is 1 and
  // this is exactly the hardware's behaviour.
  reg vbl_irq, vblank_d, iack_q;
  wire iack_end = iack_q && !cpu_iack;
  always @(posedge clk) begin
    if (rst) begin
      vbl_irq  <= 1'b0;
      vblank_d <= 1'b0;
      iack_q   <= 1'b0;
    end else begin
      vblank_d <= vblank;
      iack_q   <= cpu_iack;
      if (vblank_start && ce_en) vbl_irq <= 1'b1;
      else if (iack_end)         vbl_irq <= 1'b0;  // acknowledge ended
    end
  end

  // Frames whose vblank ended with the interrupt still pending: exactly the
  // frames the old fallback fired on.  Only counted while the CPU runs.
  reg [7:0] pend_eovb;
  always @(posedge clk) begin
    if (rst) pend_eovb <= 8'd0;
    else if (vblank_d && !vblank && vbl_irq && !iack_end && ce_en &&
             pend_eovb != 8'hFF)
      pend_eovb <= pend_eovb + 8'd1;
  end

  // How many times the 68000 acknowledges an interrupt per frame.  One is
  // correct.  More than one is the bug above, and this is how it is told
  // apart from "the CPU is simply slow", which the same symptom looks like.
  reg [7:0] iack_cnt, dbg_iack_cnt;
  always @(posedge clk) begin
    if (rst) begin
      iack_cnt <= 8'd0; dbg_iack_cnt <= 8'd0;
    end else begin
      if (vblank_start) begin
        dbg_iack_cnt <= iack_cnt;
        iack_cnt     <= 8'd0;
      end else if (cpu_iack && !iack_q && iack_cnt != 8'hFF) begin
        iack_cnt <= iack_cnt + 8'd1;
      end
    end
  end

  // The same count, accumulated: a screenshot of row 68 is one frame, these
  // are every frame since reset.  Frames with no IACK include the boot
  // frames before the game enables interrupts, and every paused frame -- so
  // read this one as "stops increasing", not as "is zero".
  reg [15:0] n_iack0;
  reg [7:0]  n_iack2;
  always @(posedge clk) begin
    if (rst) begin
      n_iack0 <= 16'd0; n_iack2 <= 8'd0;
    end else if (vblank_start) begin
      if (iack_cnt == 8'd0 && n_iack0 != 16'hFFFF) n_iack0 <= n_iack0 + 16'd1;
      if (iack_cnt >= 8'd2 && n_iack2 != 8'hFF)   n_iack2 <= n_iack2 + 8'd1;
    end
  end
  assign dbg_iack_x = {n_iack0, pend_eovb, n_iack2};

  // ---------------------------------------------------------------------
  // Video
  // ---------------------------------------------------------------------
  wire [24:0] gfx1_a, gfx2_a;
  wire [15:0] gfx1_q, gfx2_q;
  wire        gfx1_req, gfx1_ack, gfx2_req, gfx2_ack;
  wire [15:0] spr_drawn, spr_hit, spr_overrun;
  wire [15:0] spr_nonrom, spr_workload;
  wire [15:0] spr_snap1, spr_snap2;

  ps_video #(.V_TOTAL(V_TOTAL), .V_VISIBLE(V_VISIBLE),
             .H_VISIBLE(H_VISIBLE), .H_TOTAL(H_TOTAL)) u_video (
      .clk(clk), .rst(rst), .ce_pix(ce_pix_r),
      .gfxbank(gfxbank), .char_palbank(char_palbank),
      .spr_palbank(spr_palbank),
      .scrolly(scrolly), .flip_screen(flip_screen),
      .gga_h({gga_regs[0], gga_regs[1], gga_regs[2],  gga_regs[3]}),
      .gga_v({gga_regs[8], gga_regs[9], gga_regs[10], gga_regs[11]}),
      .gga_h_ok(&gga_written[3:0]),
      .gga_v_ok(&gga_written[11:8]),
      .vram_addr(v_vram_a), .vram_data(v_vram_q),
      .raster_addr(v_raster_a), .raster_data(v_raster_q),
      .pal_addr(v_pal_a), .pal_data(v_pal_q),
      .spr_addr(v_spr_a), .spr_data(v_spr_q),
      .sprlut_addr(v_sprlut_a), .sprlut_data(v_sprlut_q),
      .gfx1_addr(gfx1_a), .gfx1_data(gfx1_q),
      .gfx1_req(gfx1_req), .gfx1_ack(gfx1_ack),
      .gfx2_addr(gfx2_a), .gfx2_data(gfx2_q),
      .gfx2_req(gfx2_req), .gfx2_ack(gfx2_ack),
      .red(red), .green(green), .blue(blue),
      .hsync(hsync), .vsync(vsync), .hblank(hblank), .vblank(vblank),
      .ce_pix_out(),
      .vblank_start(vblank_start),
      .dbg_tm_late(dbg_tm_late),
      .dbg_tm_late_l(dbg_tm_late_l),
      .dbg_crtc(dbg_crtc),
      .dbg_hcnt(dbg_hcnt), .dbg_vcnt(dbg_vcnt),
      .dbg_spr_drawn(spr_drawn), .dbg_spr_hit(spr_hit),
      .dbg_spr_overrun(spr_overrun),
      .dbg_spr_snap1(spr_snap1),
      .dbg_spr_snap2(spr_snap2),
      .dbg_spr_nonrom(spr_nonrom),
      .dbg_spr_workload(spr_workload),
      .dbg_raster_msg(dbg_raster_msg),
      .dbg_raster_court(dbg_raster_court),
      .dbg_o6_map(dbg_o6_map),
      .dbg_o6_tile(dbg_o6_tile),
      .dbg_o6_pos(dbg_o6_pos),
      .dbg_o6_first(dbg_o6_first),
      .dbg_o6_sx(dbg_o6_sx),
      .dbg_o6_blitx(dbg_o6_blitx),
      .dbg_o6_row0(dbg_o6_row0),
      .dbg_o6_row1(dbg_o6_row1),
      .dbg_o6_row2(dbg_o6_row2),
      .dbg_o6_row3(dbg_o6_row3)
  );

  // ---------------------------------------------------------------------
  // Sound board
  //
  // The Z80's 128 K program ROM is BRAM and is filled by snooping the
  // download stream as it goes past on its way to SDRAM.  The copy in SDRAM
  // is left in place: it costs nothing, and it means the ROM probe could be
  // pointed at the sound region too if the two ever had to be compared.
  //
  // dl_ack is the arbiter's ack for client 0, so this fires exactly once per
  // word actually taken by the memory bus.  Gating on dl_req as well matters:
  // client 0 is shared with the ROM probe once the download is over.
  // ---------------------------------------------------------------------
  wire        snd_pending;
  wire [19:1] pcma_a;
  wire [17:1] pcmb_a;
  wire        pcma_req, pcma_ack, pcmb_req, pcmb_ack;

  wire        dl_in_snd = dl_active && (dl_addr >= SNDROM_BASE_W) &&
                          (dl_addr <  SNDROM_BASE_W + 25'h10000);
  wire        snd_rom_we = dl_in_snd & dl_req & arb_ack[0];
  // Explicit slice, not a mask: `(dl_addr - BASE) & 25'hFFFF` assigned to a
  // 16-bit target is a truncation Quartus warns about, and the project targets
  // zero project-owned warnings.  The named 25-bit intermediate makes the
  // narrowing deliberate and silent.
  wire [24:0] snd_rom_off = dl_addr - SNDROM_BASE_W;
  wire [15:0] snd_rom_wa  = snd_rom_off[15:0];

  ps_sound u_sound (
      .clk(clk), .rst(rst), .rom_rst(mem_rst), .ce_en(ce_en),
      .frame(vblank_start),
      .rom_we(snd_rom_we), .rom_wa(snd_rom_wa), .rom_wd(dl_data),
      .latch_din(sound_latch), .latch_we(sound_latch_we),
      .latch_pending(snd_pending),
      .adpcma_a(pcma_a), .adpcma_q(arb_dout),
      .adpcma_req(pcma_req), .adpcma_ack(pcma_ack),
      .adpcmb_a(pcmb_a), .adpcmb_q(arb_dout),
      .adpcmb_req(pcmb_req), .adpcmb_ack(pcmb_ack),
      .snd_l(snd_l), .snd_r(snd_r),
      .dbg_z80_cyc(dbg_z80_cyc), .dbg_ym_wr(dbg_ym_wr),
      .dbg_pcma_fetch(dbg_pcma_fetch), .dbg_pcm_late(dbg_pcm_late),
      .dbg_state(dbg_snd_state),
      .dbg_rom_w0(dbg_snd_rom_w0), .dbg_rom_n(dbg_snd_rom_n),
      .dbg_peak(dbg_snd_peak), .dbg_latch_ack(dbg_snd_latch_ack),
      .dbg_roe_a(dbg_snd_roe_a),
      .dbg_peak_op(dbg_snd_peak_op),
      .dbg_aon_cnt(dbg_snd_aon_cnt),
      .dbg_eg_min(dbg_snd_eg_min),
      .dbg_keyon_cnt(dbg_snd_keyon_cnt),
      .dbg_mmr_kon(dbg_snd_mmr_kon),
      .dbg_kon_latch(dbg_snd_kon_latch),
      .dbg_kon_match(dbg_snd_kon_match),
      .dbg_csr_slots(dbg_snd_csr_slots),
      .dbg_fm_koff(dbg_snd_fm_koff),
      .dbg_last_kon(dbg_snd_last_kon),
      .dbg_late_fr(dbg_pcma_late_fr),
      .dbg_pcmb_fr(),
      .dbg_jump_fr(dbg_jump_fr),
      .dbg_jump_a(),
      .dbg_jump_b(),
      .dbg_maxd_fr(dbg_maxd_fr),
      .dbg_pcmb_late_fr(),
      .dbg_fetch_fr(dbg_pcma_fetch_fr),
      .dbg_peak_l(dbg_snd_peak_l),
      .dbg_peak_r(dbg_snd_peak_r),
      .dbg_pcma_kon(dbg_snd_pcma_kon),
      .dbg_fm_kon(dbg_snd_fm_kon),
      .dbg_sample(dbg_snd_sample),
      .dbg_io_rd(dbg_snd_io_rd),
      .dbg_last_b1(dbg_snd_last_b1),
      .dbg_irq(dbg_snd_irq),
      .dbg_intack(dbg_snd_intack),
      .dbg_timer_w(dbg_snd_timer_w),
      .dbg_peak_fm(dbg_snd_peak_fm),
      .dbg_peak_psg(dbg_snd_peak_psg)
  );

  // ---------------------------------------------------------------------
  // ROM probe -- "is what reached SDRAM what the builder produced?"
  //
  // The .mra and tools/build_rom.py must agree byte for byte, and once they
  // did not: the 68000 image came out byteswapped because the MRA interleave
  // map meant the opposite of what was assumed.  That was only caught because
  // the reset vector is a known value.  gfx2 has no such landmark, so this
  // reads two words straight out of SDRAM after the download and shows them.
  //
  // Probe address and expected values come from roms/pspikes.bin, chosen as
  // the first place where the two possible g7j/g7l pairings differ:
  //     word 0x06003A   correct FFFF FF3F   swapped FF3F FFFF
  //
  // It borrows arbiter client 0 -- the DOWNLOAD slot, which is idle once the
  // download has finished and is the HIGHEST priority.  It was on client 4
  // first and read 0000 both times, which was not "gfx2 is zeros": client 4
  // sits below the CPU, the tilemap and the sprite engine in a strict
  // priority arbiter, and those three never stop asking, so it was simply
  // never granted.  ps_memarb's own header warns about exactly that.
  //
  // probe_done is reported separately (overlay row 15 bit 12) so that a
  // reading of 0000 can never again mean two different things.
  // ---------------------------------------------------------------------
  localparam [24:0] PROBE_ADDR = GFX2_BASE_W + 25'h3A;

  reg [24:0] probe_addr;
  reg        probe_req;
  reg [15:0] probe_w0, probe_w1;
  reg [1:0]  probe_st;
  reg [19:0] probe_wait;
  wire       probe_done = (probe_st == 2'd3);

  always @(posedge clk) begin
    if (rst) begin
      probe_st   <= 2'd0;
      probe_req  <= 1'b0;
      probe_w0   <= 16'd0;
      probe_w1   <= 16'd0;
      probe_wait <= 20'd0;
    end else begin
      // DO NOT wait for a falling edge of dl_active.  This module is held in
      // `rst` (the system reset) for the whole ROM download -- MiSTer asserts
      // RESET while ROMs load -- so by the time the reset releases, that edge
      // has already happened and is unobservable from here.  An earlier
      // version watched for it and never fired, and only the probe_done bit
      // told the difference between that and "gfx2 really is zeros".
      //
      // Instead: once out of reset and not downloading, count a while and go.
      if (!dl_active && !probe_wait[19]) probe_wait <= probe_wait + 20'd1;
      case (probe_st)
        2'd0: if (probe_wait[19]) begin
                probe_addr <= PROBE_ADDR;
                probe_req  <= 1'b1;
                probe_st   <= 2'd1;
              end
        2'd1: if (probe_gnt) begin
                probe_w0   <= arb_dout;
                probe_addr <= PROBE_ADDR + 25'd1;
                probe_st   <= 2'd2;
              end
        2'd2: if (probe_gnt) begin
                probe_w1  <= arb_dout;
                probe_req <= 1'b0;
                probe_st  <= 2'd3;
              end
        default: ;
      endcase
    end
  end

  wire probe_gnt = arb_ack[0] & probe_req & ~dl_req;

  assign dbg_rom_w0 = probe_w0;
  assign dbg_rom_w1 = probe_w1;
  assign dbg_probe_done = probe_done;

  // ---------------------------------------------------------------------
  // Memory arbiter
  //
  // Client order matches ps_memarb's documented priority.  Client 6 (z80) is
  // permanently idle: the sound CPU runs from BRAM, so it never competes for
  // the memory bus.  The slot is kept rather than removed so the numbering in
  // ps_memarb's header still describes what is here.
  // ---------------------------------------------------------------------
  localparam int NC = 7;
  wire [NC-1:0]      arb_req, arb_we, arb_ack, arb_urgent;
  wire [25*NC-1:0]   arb_addr;
  wire [16*NC-1:0]   arb_din;
  wire [2*NC-1:0]    arb_ds;
  wire [15:0]        arb_dout;

  //  0 download   1 sprite   2 tilemap   3 cpu   4 adpcma   5 adpcmb   6 z80
  // Tilemap (gfx1) is client 1 and sprite (gfx2) client 2 -- the deadlines
  // were inverted; see the header of ps_memarb.sv.
  assign arb_req  = {1'b0, rc_rd, pcmb_req, pcma_req,
                     gfx2_req, gfx1_req, dl_req | probe_req};
  assign arb_we   = {6'b000000, dl_active};

  // ADPCM-A's deadline override.  jt10 moves its sample address every ~60
  // clocks and takes whatever is on the pins at the end of that; a byte that
  // arrives late is a wrong nibble, amplified 7.25x by jt10_acc on its way
  // into the mix (DEBUG_LOG O13).  So let this one client jump the queue --
  // and only after it has already waited long enough that losing again would
  // put it past the deadline.
  //
  // 24 of ~60 clocks: it still loses the common case to the sprite and
  // tilemap engines, which is the point -- their own deadlines are what
  // O11 was about.  `dbg_pcm_late` is the check that this worked, and
  // `dbg_tm_late` and `dbg_overrun` are the check that it cost nothing.
  localparam [5:0] PCMA_URGENT_AFTER = 6'd24;
  reg [5:0] pcma_age;
  always @(posedge clk) begin
    if (rst)                        pcma_age <= 6'd0;
    else if (!pcma_req)             pcma_age <= 6'd0;
    else if (pcma_ack)              pcma_age <= 6'd0;
    else if (pcma_age != 6'h3F)     pcma_age <= pcma_age + 6'd1;
  end
  wire pcma_urgent = pcma_req && (pcma_age >= PCMA_URGENT_AFTER);

  //                z80   cpu   pcmb  pcma          tile  spr   dl
  // ADPCM-A IS THE ONLY CLIENT THAT MAY JUMP THE QUEUE.
  //
  // The sprite engine used to assert urgent as well, on a line whose render
  // had passed 1,200 of its 2,549 clocks -- "which a healthy line never
  // reaches".  That premise was true when it was written and stopped being
  // true one commit later.  Decoupling the blitter (DEBUG_LOG O17) took the
  // 608 idle S_BLIT clocks out of a busy line and made `rom_req` continuous,
  // so a 38-row line now finishes near clock 1,700 -- and every such line
  // spends its last ~500 clocks urgent, outranking the tilemap, while being
  // in no trouble whatsoever.
  //
  // The tilemap loads its shifter 39 clocks after it asks, arrived or not, so
  // 500 clocks of losing is ~90 pixels of background drawn from the previous
  // tile row.  That is O11 exactly, at the other end of the line: measured
  // 2026-09-02 over 20 attract frames,
  //
  //     row 69  tilemap deadline misses per frame   0 .. 383
  //     row 57  ...of those, in the first third     0    on every frame
  //     row 20  sprite line overruns                0    on all 10 samples
  //
  // The first third is where O11's misses were (ratio 1.00) and there are
  // none there now; the sprite engine, meanwhile, is not missing its own
  // deadline at all.  So the override protects nothing and costs up to 383
  // corrupted tile rows a frame.  It goes.  `dbg_overrun` is the check that
  // taking it away costs nothing -- it was 0 with the override and must stay
  // 0 without it (O11: both halves matter).
  assign arb_urgent = {1'b0, 1'b0, 1'b0, pcma_urgent, 1'b0, 1'b0, 1'b0};
  // Each field must be exactly 25 bits.  A concatenation that is one field
  // too wide truncates from the MSB and silently shifts every client's
  // address down a slot, which reads as "the CPU fetches garbage".
  wire [24:0] cpu_rom_word = MAINCPU_BASE_W + {8'd0, rc_a};
  wire [24:0] pcma_word    = ADPCMA_BASE_W + {6'd0, pcma_a};
  wire [24:0] pcmb_word    = ADPCMB_BASE_W + {8'd0, pcmb_a};

  assign arb_addr = {25'd0,          // client 6: z80 -- runs from BRAM
                     cpu_rom_word,   // client 5: cpu
                     pcmb_word,      // client 4: adpcmb
                     pcma_word,      // client 3: adpcma
                     gfx2_a,         // client 2: sprite
                     gfx1_a,         // client 1: tilemap
                     dl_req ? dl_addr : probe_addr};  // client 0: download,
                                     // then the ROM probe once it is idle
  assign arb_din  = {96'd0, dl_data};
  assign arb_ds   = {12'd0, 2'b11};

  assign dl_ack      = arb_ack[0];
  assign gfx1_ack    = arb_ack[1];
  assign gfx2_ack    = arb_ack[2];
  assign pcma_ack    = arb_ack[3];
  assign pcmb_ack    = arb_ack[4];
  assign rc_ack      = arb_ack[5];
  assign gfx2_q      = arb_dout;
  assign gfx1_q      = arb_dout;
  assign rc_q        = arb_dout;

  ps_memarb #(.N(NC)) u_arb (
      .clk(clk), .rst(mem_rst),
      .req(arb_req),
      .urgent(arb_urgent), .addr(arb_addr), .din(arb_din),
      .we(arb_we), .ds(arb_ds), .ack(arb_ack), .dout(arb_dout),
      .m_addr(mem_addr), .m_din(mem_din), .m_dout(mem_dout),
      .m_req(mem_req), .m_we(mem_we), .m_ds(mem_ds), .m_ack(mem_ack),
      .dbg_cpu_stall(dbg_cpu_stall)
  );

  // ---------------------------------------------------------------------
  // Does the game write video RAM while the screen is being drawn?
  //
  // A user watching the board reports that STATIC screens are clean and
  // MOVING things flicker -- the crowd during a rally, and the player
  // portraits as they slide in and out on the insert-coin screen.  Things
  // that move are the things whose sprite and tilemap words are rewritten
  // every frame, so the suspect is WHEN they are rewritten relative to the
  // scan.
  //
  // MAME cannot answer this: it renders a whole frame from one snapshot at
  // screen_update time and never sees the race.  Real hardware reads live,
  // like this core -- so if the game writes during vblank and these counters
  // stay at zero, the timing agrees and the flicker is something else.  If
  // they count, this core's display window and the game's write window
  // disagree, and docs/HARDWARE.md already flags the video totals as
  // INFERRED and the GGA registers as UNVERIFIED.
  // ---------------------------------------------------------------------
  // How many LINES after vblank starts does each region's last write land?
  //
  // PER REGION, not ORed together.  The first version ORed sprite, tilemap,
  // raster and palette writes and remembered the last of them -- and the same
  // mistake, made first in the MAME lua, is what produced a "burst width" of
  // p99 33.9 lines that turned out to be a sparse VRAM trickle dragging the
  // last write to the bottom of the screen.  Asked per region, MAME says
  // raster and palette always finish inside blanking and only sprite and
  // tilemap ever run past it.  So only those two are worth a row here.
  //
  // MAME measured the same quantity on the same game, with an unobstructed
  // 68000: sprite median 7.6 lines, p99 34.2, max 89.0, and tilemap present
  // on only 24 frames of 539 and past line 16 on every one of them.  A number
  // much larger here says this core's arbiter is stretching the burst; a
  // number that matches says the game does this on real hardware too.
  // docs/DEBUG_LOG.md O10.
  wire [8:0] lines_since_vbl = (dbg_vcnt >= V_VISIBLE)
                             ? (dbg_vcnt - V_VISIBLE)
                             : (dbg_vcnt + (V_TOTAL - V_VISIBLE));

  // The 68000's per-frame ROM wait counters lived here.  Their question is
  // closed: 7.19 system clocks of wait per fetch, 21.7 % of the blank
  // interval, brought to 4.76 by the ROM cache (DECISIONS D12).  Their
  // overlay rows now carry ADPCM-B, which has never been measured at all.

  reg [7:0] spr_end;                 // last sprite write, this frame so far

  // ...and where the burst STARTS, which is what separates the two
  // explanations for it ending at line 23-25 where MAME's ends at 7.6.
  //
  //   starts near line 0   -> the burst is ~23 lines wide against MAME's ~7,
  //                           so this core's 68000 really is that much slower
  //   starts near line 16  -> the burst is the SAME width as MAME's and simply
  //                           begins 16 lines late, which is an interrupt-phase
  //                           fault, not a speed one
  //
  // Worth measuring rather than reasoning about, because the ROM-throughput
  // counters say this CPU is only 1.33x slower than MAME's, and 1.33 does not
  // produce 3.1.  Two of my own instruments disagree; this is the third.
  // ...and HOW MANY sprite words the frame writes, because "the burst is
  // wider than MAME's" is only a statement about speed if the work is the
  // same.  MAME, over the whole 57-second attract loop, writes 65+ words on
  // 2268 of 3479 frames and finishes those by line 10.2 (p90 16.4, max 18.2);
  // this board finishes at 24.  If the board is writing far more words than
  // any MAME frame, the difference is the scene, not the core.
  reg [15:0] dbg_overrun_fr;
  localparam [8:0] V_BLANK_LINES = V_TOTAL - V_VISIBLE;   // 16 blanking lines

  reg       spr_seen;
  reg [7:0] spr_beg;
  reg [7:0] spr_first;   // the tilemap's first-write line lost its overlay
                         // row to the IACK count and is no longer tracked

  always @(posedge clk) begin
    if (rst) begin
      spr_end   <= 8'd0;
      spr_beg   <= 8'hFF;
      spr_first <= 8'hFF;
      spr_seen  <= 1'b0;
      dbg_overrun_fr <= 16'd0;
    end else if (vblank_start) begin
      // Frames whose sprite burst ran past the last blanking line, counted
      // over every frame rather than sampled one screenshot at a time.
      // Sampling cannot see this tail: 30 single-frame reads found one frame
      // at line 34 and no way to say whether that is one frame in 30 or one
      // in 3000, and the difference is whether a viewer sees it.  Two
      // screenshots N seconds apart give the rate over N * 61.31 frames.
      // `>=`, not `>`.  lines_since_vbl maps vcnt 0 -- the FIRST VISIBLE
      // line -- to exactly V_BLANK_LINES, so `>` was blind to a whole
      // scanline of the defect this counter exists to count.
      if ({1'b0, spr_end} >= V_BLANK_LINES && dbg_overrun_fr != 16'hFFFF)
        dbg_overrun_fr <= dbg_overrun_fr + 16'd1;
      spr_first  <= spr_beg;
      spr_end   <= 8'd0;
      spr_beg   <= 8'hFF;                        // FF = no write this frame
      spr_seen  <= 1'b0;
    end else begin
      if (|c_spr_we) begin
        spr_end <= lines_since_vbl[7:0];
        if (!spr_seen) begin spr_beg <= lines_since_vbl[7:0]; spr_seen <= 1'b1; end
      end
    end
  end

  assign dbg_vbl_irq = vbl_irq;
  assign dbg_gga         = {gga_regs[0], gga_regs[8]};
  assign dbg_gga_x       = {gga_regs[1], gga_regs[9],  gga_regs[2], gga_regs[10],
                            gga_regs[3], gga_regs[11], gga_regs[4], gga_regs[12]};
  assign dbg_spr_drawn   = spr_drawn;
  assign dbg_spr_hit     = spr_hit;
  assign dbg_spr_overrun = spr_overrun;
  assign dbg_spr_snap1    = spr_snap1;
  assign dbg_spr_snap2    = spr_snap2;
  assign dbg_spr_nonrom   = spr_nonrom;
  assign dbg_spr_workload = spr_workload;
  // Rows 21 and 22 were the ROM-download request/ack counters, which answer a
  // boot-time question this core stopped having once it booted.  They carry
  // the sprite overrun probe now, and they sit on the SAME overlay page as the
  // overrun itself (row 20) so one screenshot answers the whole question.


  // Row 68 low byte was `vram_first`, which reads FF on nearly every frame
  // because the game rewrites the tilemap on only about one frame in twenty.
  // The IACK count earns the space instead: it is the regression guard for
  // DEBUG_LOG O10, and an interrupt that starts being taken twice again would
  // otherwise be invisible until the flicker came back.
  assign dbg_burst_first = {spr_first, dbg_iack_cnt};
  // Row 69 gave up the per-frame sprite word count.  That question is
  // answered -- 186-273 before the interrupt fix, 17-113 after, which is what
  // proved the handler had been running twice -- and the tilemap's fetch
  // deadline has never been measured at all.  ps_video drives the port.
  // Row 57 carried the game's write-burst end.  That question is closed and
  // verified (DEBUG_LOG O10), and the tilemap deadline needs a second reading
  // more than the burst needs a third.
  assign dbg_sprwr_disp  = dbg_tm_late_l;
  // Row 65 gave up {IACK count, worst burst end}: the IACK count has read 1 in
  // every one of 50 samples since the acknowledge fix, and the worst-since-reset
  // figure is dominated by boot.  The overrun FRAME COUNT is the number that
  // still has something to say.
  assign dbg_vramwr_disp = dbg_overrun_fr;
  assign dbg_gfxbank     = gfxbank;
  assign dbg_sound_latch = sound_latch;

endmodule


//----------------------------------------------------------------------------
//  True dual-port RAM: port A read/write (CPU), port B read-only (video).
//  One clock of read latency on both ports.
//----------------------------------------------------------------------------
module ps_dpram #(parameter int AW = 11) (
    input  wire            clk,
    input  wire [AW-1:0]   a_addr,
    input  wire [15:0]     a_din,
    input  wire [1:0]      a_we,
    output reg  [15:0]     a_dout,
    input  wire [AW-1:0]   b_addr,
    output reg  [15:0]     b_dout
);
  reg [7:0] hi [0:(1<<AW)-1];
  reg [7:0] lo [0:(1<<AW)-1];

  always @(posedge clk) begin
    if (a_we[1]) hi[a_addr] <= a_din[15:8];
    if (a_we[0]) lo[a_addr] <= a_din[7:0];
    a_dout <= {hi[a_addr], lo[a_addr]};
    b_dout <= {hi[b_addr], lo[b_addr]};
  end
endmodule

`default_nettype wire
